### ISSUE TITLE
Multiple definitions for the Webhooks.update() method

### ISSUE THREAD

**Issue by stebunovd** [tghw/trello-py#12]
See [this](https://github.com/tghw/trello-py/blob/82eedf428dc1cb5d98e42372eee537969fdd9253/trello/webhooks.py#L24-L26) and [this](https://github.com/tghw/trello-py/blob/82eedf428dc1cb5d98e42372eee537969fdd9253/trello/webhooks.py#L32-L34). There are two `.update()` methods in the `Webhooks` class that take different parameters. Looks like a Java-style pattern. However, in Python, it doesn't work like in Java - the second method definition simply overrides the previous one. The result is confusing: by looking at code, you may think that there's a method for updating a webhook by its ID, but in practice, there isn't because it was overridden by the second definition below.

**Comment by tghw** [comment]
Thanks for reporting. I'm well aware that Python does not support overloading methods the same way Java does. This code was initially created via an automated process based on the documentation, which at the time included two updates.

**Comment by stebunovd** [comment]
I see, thanks for the context. So... is the code auto-generation still a thing? Any plans to have a method for updating a webhook by its ID?

**Comment by tghw** [comment]
Code generation is no longer a thing. It was useful for first creating the API, but there are enough corner cases that it's not worth maintaining the generation over just fixing the API. The current `Webhooks.update()` method takes the webhook id as its first and only required parameter.

See https://github.com/tghw/trello-py/blob/06b0bbc5d3f5ee7d586cc6d5c7dbadedc81bbd1e/trello/webhooks.py#L24

**Comment by stebunovd** [comment]
oh, I didn't realize that you already fixed that. Sounds great, thank you for the patch! 

Just a minor item that I noticed - I guess the `.update_()` method a few lines below will stop working. It's mentioned there that it's for backward compatibility, so not sure if anyone is still using it. If not, maybe it can be removed too?

**Comment by tghw** [comment]
It will get removed eventually, but not yet. Currently there is no downside to keeping it around.

If I have some time later this year I might go through the code to clean everything up, remove the deprecated code, and declare a version 1.0, but for now it seems to be useful as is.
