### ISSUE TITLE
403 Response on GET requests to trello due to breaking change at atlassian

### ISSUE THREAD

**Issue by kod2nd** [tghw/trello-py#19]
Trello’s API will no longer permit supplying a body with a GET request. Previous behavior in our API ignored the payloads provided with GET requests but these requests will now be blocked with a 403 response from our content delivery network.

To resolve issues resulting from this change ensure all GET requests to Trello’s API are sent without a payload.

https://developer.atlassian.com/changelog/#CHANGE-1459

Setting data to none on GET seems to fix it

```python

# inside trelloclient.py

def fetch_json(
...
...
# set content type and accept headers to handle JSON
if http_method in ("POST", "PUT", "DELETE") and not files:
    headers['Content-Type'] = 'application/json; charset=utf-8'

headers['Accept'] = 'application/json'

# ADD THIS PART HERE
if http_method in ("GET"):
    data = None

```

Hope this helps someone

**Comment by tghw** [comment]
@kod2nd Can you tell me what call is using GET with a body? There is no `trelloclient.py` in this project.

**Comment by kod2nd** [comment]
Sorry confused the projects! Will close the issue.
