### ISSUE TITLE
Has this code worked since 3666d8ab?

### ISSUE THREAD

**Issue by wcooley** [tghw/trello-py#3]
I am confused because it seems that this code has been invalid since commit 3666d8ab in 2012, when it was regenerated. Yet people have submitted minor patches since then, none of which fix the glaring syntax problem.

Am I missing something? I tried with Python 3.4.3  and hit the obivous (unless slashes in variable names are a Python 3 feature that I have not read about and the error is elsewhere) syntax error:

```
$ python -m trello
Traceback (most recent call last):
  File "/Users/wcooley/anaconda/envs/python-3.4/lib/python3.4/runpy.py", line 151, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/Users/wcooley/anaconda/envs/python-3.4/lib/python3.4/runpy.py", line 118, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/Users/wcooley/anaconda/envs/python-3.4/lib/python3.4/runpy.py", line 104, in _get_module_details
    spec = importlib.util.find_spec(mod_name)
  File "/Users/wcooley/anaconda/envs/python-3.4/lib/python3.4/importlib/util.py", line 86, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/Users/wcooley/src/trello-py/trello/__init__.py", line 3, in <module>
    from .boards import Boards
  File "/Users/wcooley/src/trello-py/trello/boards.py", line 96
    def update(self, board_id, name=None, desc=None, closed=None, subscribed=None, idOrganization=None, prefs/permissionLevel=None, prefs/selfJoin=None, prefs/cardCovers=None, prefs/invitations=None, prefs/voting=None, prefs/comments=None):
                                                                                                             ^
SyntaxError: invalid syntax
```

I think the fix should be easy enough -- substitute invalid characters in variable names, but I am unclear if this is code anyone is actually using or I should look for something elsewhere more actively maintained?

**Comment by tghw** [comment]
This repository has not been actively maintained for some time, but I am happy to accept pull requests or coordinate with someone who wants to take over as the project maintainer.

**Comment by jean** [comment]
@wcooley I just ran into this too :-)  
I think the fix should be passing something like `data={'name': name, ... 'prefs/permissionLevel': prefs['permissionLevel'], 'prefs/selfJoin': prefs['selfJoin'], ...}`
I.e. parsing the API docs into dicts if there's a slash in the name.
I'll look into this more if I go with this package (surveying a bunch of Python Trello clients now ..)

**Comment by tclh123** [comment]
You should mention "the client is NOT WORK NOW!!" in README.
