### ISSUE TITLE
Could we get 0.9.2 pushed to PyPi?

### ISSUE THREAD

**Issue by peterkh** [tghw/trello-py#8]
Hi,

Looks like it has fixed a few issues including Python 3 support which would be super handy. Any chance we could get this version uploaded to PyPi?

Thanks!

**Comment by ledzep4pm** [comment]
This wold be great to have,

**Comment by ivanhercaz** [comment]
@peterkh @ledzep4pm, I think this issue can be closed because its maintainer, @tghw, already uploaded the [latest release to PyPI](https://pypi.org/project/trello/#history) at the May 23, 2019.

**Comment by ivanhercaz** [comment]
Although looking the latest release date in PyPI and the latest commit in this repository, both dates doesn't match... for two years!

**Comment by tghw** [comment]
0.9.4 is released
