### ISSUE TITLE
Version 0.9.3 is missing requests dependency

### ISSUE THREAD

**Issue by mark-edf** [tghw/trello-py#9]
I've installed 0.9.3 but it isn't pulling down `Requests` package automatically when I install it. It looks like it is just missing from the setup.py (see attached) even though you have it listed in the master version which is labelled 0.9.2

[setup.zip](https://github.com/tghw/trello-py/files/3215751/setup.zip)

**Comment by ivanhercaz** [comment]
This happens to me too installing this package with `pip`.

**Comment by tghw** [comment]
Fixed in 0.9.4
